export const LOCATION_CONSTANT = {
    GET_LOCATION_LIST: 'GET_LOCATION_LIST',
    SET_LOCATION_LIST: 'SET_LOCATION_LIST',
    GET_LOCATION_LIST_ERROR: 'GET_LOCATION_ERROR',
    GET_LOCATION_ID: 'GET_LOCATION_ID',
    SET_LOCATION_ID_LIST: 'SET_LOCATION_ID_LIST',
    GET_LOCATION_ERROR: 'GET_LOCATION_ERROR'
}